### ISSUE TITLE
Display events managed in the Calendar app

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Timeline#4]
As discussed in https://github.com/Starcounter/Minutes/issues/56, Timeline should display events managed in the Calendar app. 

When this is done, perhaps we can remove the "meetings" feature from Timeline? Or replace "meetings" feature with "notes" feature, by merging the Notes app into the Timeline app.

My goal here is to:

- reuse the prefabs that we have, whenever it makes sense
- reduce the number of apps we are maintaining

Please discuss this with @PatrykSzwer

**Comment by Joltrix** [comment]
Are we sure we want to merge the Notes app into the Timeline app?
The notes app isn't that advanced, nor does it have a lot of code. So it should be really easy to just move everything to the Timeline app.

But even so, the notes app creates events (albeit simple "write something here" events). But shouldn't the timeline only _display_ events? Why would we want to be able to create some (for example Notes) events, but not other events such as customer events?

Regarding the meetings "app".
I've only copy pasted the code from Notes, created a new app, and changed the database class to "MeetingEvent". Just to see how Timeline handles multiple event types.
I only use the meeting app locally, for testing purposes :D

**Comment by warpech** [comment]
I am not sure, which is why I wrote "perhaps" ;)

I thought that right now the "meeting app" does not exist, but now I understand that you actually have 3 apps: Timeline, Meetings, Notes. That is too much to maintain, given that we also have Calendar and Content. So what can we do to reduce that number?

**Comment by Joltrix** [comment]
Meeting can/will be removed! :) That way there's 1 less app to worry about. At least until we want to implement an actual meeting application. There was a "meeting" event in the mockup images, so that's why I named it meetings.

Once Timeline works with Calendar and Content, we can remove Meeting, and possibly Notes(if Content app can do what Notes can)

**Comment by warpech** [comment]
I am glad that we have this, since Calendar and Content show two completely different problems.

Calendar (much like Timeline) knows about events. The purpose of the Calendar app is just to render events on a 2-dimensional grid that humans call a "calendar". Likewise, the purpose of the Timeline app is to render events on a 1-dimensional axis that humans call a "timeline".

"Meeting" is just a *kind* of event that should be understood both by Calendar and Timeline.

**Comment by Joltrix** [comment]
I have been working on different branches and making the Timeline work with calendar and changing how the deletion works.

The following Pull Requests needs to be merged in order to make everything work:

[People PR](https://github.com/StarcounterApps/People/pull/117)
[Calendar PR](https://github.com/StarcounterApps/Calendar/pull/77)
[Timeline PR](https://github.com/StarcounterApps/Timeline/pull/20)
[Simplified PR](https://github.com/StarcounterApps/Simplified/pull/67)

@bouguila Assigning these Reviews to you :)

**Comment by Joltrix** [comment]
Since all of these PRs have been merged, I'll go ahead and close this issue.

Meetings app have been removed, and all the calendar events will appear in the timeline :)
