### ISSUE TITLE
Do the code review

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Timeline#5]
As discussed in https://github.com/Starcounter/Minutes/issues/56, @habib535 please do the code review of the Timeline app. The best is to do that before Thursday, so that @Joltrix has a chance to respond to it.

Since the changes are on `master` branch (not PR), the review can be made directly as comments in https://github.com/StarcounterApps/Timeline/commits/master (click on any commit and then you can add a comment on a particular line that was changed). Or in this issue, below.

**Comment by habib535** [comment]
Hey @Joltrix , I know that this is still in progress, below are a few observations. Please note that majority of them are just nice to have points :)

- I am unable to run it because gives the following error, do I need to upgrade starcounter version?
'Event' does not contain a definition for 'Participants'

- All the internal / inline css can be moved to new file style.css

- ActionsPage.html
The CleanupTrigger is only going to be invoked once because after the first time setting value to 1 again is not going to trigger the Handle method.

- MainHandlers.cs
We can add the `HandlerOptions - Selfonly` Flag for Handlers that will be invoked only from internal codehost calls.
`Blender mapping` can be moved to a new method/class to meet the separation of concern principle

- HelperFunctions.cs
We can use the `Db.SQL(…).First` instead of converting an IEnumerable to List first and then getting the first matched event. The same can be done in `Handle(Input.CleanupTrigger Action)` of ActionsPage.json.cs

- EventListPage.json
I don't know the exact scenario but the Json looks a little repetitive to me.

**Comment by warpech** [comment]
> I am unable to run it because gives the following error, do I need to upgrade starcounter version?
'Event' does not contain a definition for 'Participants'

You need the current version of Simplified data model (https://github.com/StarcounterApps/Simplified/commit/87a62bbbacc1b3e40b149911c8ad45d30d1b30dc). Either build it locally (it will replace the version shipped with Starcounter), or get Starcounter version newer than 2017-06-26

**Comment by warpech** [comment]
@habib535 will do the code review based on what's currently in `master` branch.

@Joltrix what's the status of the branch `event-group-experiment`?

**Comment by habib535** [comment]
Code looks good to me. Tested the basic functionality and is working fine.
Only the second last point (HelperFunctions.cs) is remaining. This needs to be filtered via SQL query instead of LINQ as it looks performance hit to me.

**Comment by warpech** [comment]
Could you pls convert that to a separate issue? Then this issue can be closed as far as I understand.

**Comment by habib535** [comment]
https://github.com/StarcounterApps/Timeline/issues/8

**Comment by habib535** [comment]
Closing as done.
